FilterConfig.add('.notif', [
  { :label => 'apple',       :has => ['from:insideicloud.icloud.com'] },
  { :label => 'coff-bag',    :has => ['from:(coffeemeetsbagel.com)'] },
  { :label => 'dropbox',     :has => ['from:dropbox.com'] },
  { :label => 'eventbrite',  :has => ['from:eventbrite.com'] },
  { :label => 'facebook',    :has => ['from:facebookmail.com'] },
  { :label => 'foursquare',  :has => ['from:foursquare.com'] },
  { :label => 'gcal',        :has => ['from:calendar-notification@google.com'] },
  { :label => 'github',      :has => ['list:"github.com"'] },
  { :label => 'google',      :has => ['from:@google.com'] },
  { :label => 'ifttt',       :has => ['from:ifttt.com'] },
  { :label => 'linkedin',    :has => ['from:linkedin.com'] },
  { :label => 'meetup',      :has => ['from:meetup.com'] },
  { :label => 'newrelic',    :has => ['from:newrelic.com'] },
  { :label => 'okcupid',     :has => ['from:okcupid -subject:("This week\'s top matches"|"New matches")'], :star => true },
  { :label => 'okcupid',     :has => ['from:okcupid subject:("This week\'s top matches"|"New matches")'], :archive => true },
  { :label => 'potsmates',   :has => ['list:"postmates.com"'] },
  { :label => 'trello',      :has => ['from:trello.com'] },
  { :label => 'twitter',     :has => ['from:(twitter.com)'] },
])
